### ISSUE TITLE
Missing FontAwesomeIcons.adobe

### ISSUE THREAD

**Issue by stwonary** [dengyin2000/dynamic_widget#45]
This Icon has been deleted from FontAwesome

https://fontawesome.com/icons/adobe

```
|-- dynamic_widget 2.0.3
|   |-- flutter...
|   |-- font_awesome_flutter 8.9.0



https://github.com/FortAwesome/Font-Awesome/blob/57005cea6da7d1c67f3466974aecd25485f60452/UPGRADING.md#5140-to-5150

## 5.14.0 to 5.15.0
--
18 |  
19 | The adobe icon has been removed by legal request of Adobe.
20 |  
21 | Font Awesome is no longer able to provide any logos or marks for the Adobe


```

# Workaround:

Use this in `pubspec.yaml`
```
dependency_overrides:
  font_awesome_flutter: 8.8.1 # https://pub.dev/packages/font_awesome_flutter
```

**Comment by stwonary** [comment]
We can lock to `font_awesome_flutter: 8.8.1` or delete this line https://github.com/dengyin2000/dynamic_widget/blob/989fc9531dd45b7d4321501c8c8cd86e2182f3f9/lib/dynamic_widget/icons_helper.dart#L1056

In my case, I'm using this icon, have no issue to delete it.

**Comment by gazreese** [comment]
With the latest flutter stable release font_awesome_flutter: 8.8.1 doesn't compile, and results in:

    Codepoint 62694 not found in font, aborting.

**Comment by gazreese** [comment]
OK so it looks like https://github.com/fluttercommunity/font_awesome_flutter/issues/122 needs to be fixed in font_awesome_flutter to work around the above 'Codepoint...' issue. This is covered by @volser here: https://github.com/volser/font_awesome_flutter/commit/ae79c08be54ba46419c7337e91047fcf4018da9c

I've forked dynamic_widget to fix the FontAwesomeIcons.adobe issue and work with the upcoming font_awesome_flutter when the issue is fixed.

If you're struggling with this build issue you can use:

```
dependency_overrides:
  font_awesome_flutter:
    git:
      url: "https://github.com/volser/font_awesome_flutter.git"
```

with:

```
dependencies:
  dynamic_widget:
    git:
      url: "https://github.com/foresightmobile/dynamic_widget"
      ref: "adobe_icon_fix"
```

To get your build up and running.
